openapi: "3.0.0"
info:
  title: Demo API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                bar:
                  description: hoho
                  value: {
                    "name": "Jane",
                    "email": "jane@doe.org"
                  }
