openapi: "3.0.0"
info:
  title: Demo API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
components:
  schemas:
    UserData:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        email:
          type: string
          example: jane@doe.org
      required: [name, email]
